name: AdvancedStructureGen
main: main.AdvancedStructureGen
description: AdvancedStructureGen descr
version: 0.1
author: JB & TK
depend:
 - MassiveCore
commands:
 asg:
  description: Use /asg to do AdvancedStructureGen stuff.